# Generated by Django 3.0 on 2020-09-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='educaton',
            new_name='education',
        ),
    ]
